[package]
name = "cryptomator-fuse-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
fuser = "0.16"
cryptomator-crypto = { path = "../cryptomator-crypto" }
tracing = "0.1"
tracing-attributes = "0.1"
libc = "0.2.177"
lru = "0.16.2"
once_cell = "1.21.3"
